// packages/web-svelte/src/routes/practice/[sessionId]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { practiceApi } from '$lib/utils/api';
	import LoadingState from '$lib/components/LoadingState.svelte';
	import ErrorState from '$lib/components/ErrorState.svelte';

	export let data;

	let loading = true;
	let questions = [];
	let currentIndex = 0;
	let selectedOptionId = null;
	let showExplanation = false;
	let submitting = false;
	let answeredQuestions = new Set();
	let flaggedQuestions = new Set();
	let streak = null;
	let error = null;
	let totalQuestions = 0;

	onMount(() => {
		// Use data from load function if available
		if (data.questions) {
			questions = data.questions;
		}
		if (data.totalQuestions !== undefined) {
			totalQuestions = data.totalQuestions;
		}
		if (data.streak) {
			streak = data.streak;
		}
		if (data.error) {
			error = data.error;
		}
		loading = false;
	});

	async function handleSubmitAnswer() {
		if (!selectedOptionId || submitting) return;

		submitting = true;
		const question = questions[currentIndex];
		if (!question) {
			submitting = false;
			return;
		}

		try {
			const sessionId = $page.params.sessionId;
			await practiceApi.submitAnswer({
				sessionId,
				questionId: question.id,
				selectedOptionId,
				timeSpentMs: 0
			});

			answeredQuestions = new Set([...answeredQuestions, question.id]);
			showExplanation = true;
		} catch (err) {
			console.error('Failed to submit answer:', err);
			error = err instanceof Error ? err.message : 'Failed to submit answer';
		} finally {
			submitting = false;
		}
	}

	function handleNext() {
		if (currentIndex < questions.length - 1) {
			currentIndex += 1;
			selectedOptionId = null;
			showExplanation = false;
		}
	}

	function handlePrevious() {
		if (currentIndex > 0) {
			currentIndex -= 1;
			selectedOptionId = null;
			showExplanation = false;
		}
	}

	function handleJumpToQuestion(index) {
		currentIndex = index;
		selectedOptionId = null;
		showExplanation = false;
	}

	async function handleFlag() {
		const question = questions[currentIndex];
		if (!question) return;

		const isFlagged = flaggedQuestions.has(question.id);

		try {
			if (isFlagged) {
				await practiceApi.unflagQuestion(question.id);
				flaggedQuestions = new Set(
					Array.from(flaggedQuestions).filter((id) => id !== question.id)
				);
			} else {
				await practiceApi.flagQuestion(question.id);
				flaggedQuestions = new Set([...flaggedQuestions, question.id]);
			}
		} catch (err) {
			console.error('Failed to flag question:', err);
		}
	}

	async function handleCompleteSession() {
		try {
			const sessionId = $page.params.sessionId;
			await practiceApi.completeSession(sessionId);
			goto('/dashboard');
		} catch (err) {
			console.error('Failed to complete session:', err);
			error = err instanceof Error ? err.message : 'Failed to complete session';
		}
	}

	$: currentQuestion = questions[currentIndex];
	$: progress = totalQuestions > 0 ? ((currentIndex + 1) / totalQuestions) * 100 : 0;
	$: isLastQuestion = currentIndex === totalQuestions - 1;
</script>

{#if loading}
	<LoadingState message="Loading practice session..." />
{:else if error}
	<ErrorState title="Practice Session Error" message={error} />
{:else if !currentQuestion}
	<ErrorState
		title="Question Not Found"
		message="Could not load the current question."
	/>
{:else}
	<div class="min-h-screen bg-gray-50">
		<nav class="bg-white border-b border-gray-200">
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
				<div class="flex justify-between h-16">
					<div class="flex items-center">
						<button
							on:click={() => window.history.back()}
							class="text-gray-700 hover:text-indigo-600"
						>
							← Back
						</button>
					</div>
				</div>
			</div>
		</nav>

		<main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
			<!-- Progress Bar -->
			<div class="mb-6">
				<div class="flex justify-between items-center mb-2">
					<span class="text-sm font-medium">
						Question {currentIndex + 1} of {totalQuestions}
					</span>
					<span class="text-sm font-medium">{Math.round(progress)}%</span>
				</div>
				<div class="w-full bg-gray-200 rounded-full h-2.5 overflow-hidden">
					<div
						class="bg-indigo-600 h-2.5 rounded-full transition-all duration-500 ease-out"
						style="width: {progress}%"
					></div>
				</div>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
				<!-- Main Question Area -->
				<div class="lg:col-span-2">
					<div class="bg-white rounded-lg shadow p-6">
						<!-- Question Header -->
						<div class="flex justify-between items-start mb-4">
							<div class="flex gap-2">
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-blue-100 text-blue-800">
									{currentQuestion.domain}
								</span>
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-purple-100 text-purple-800">
									{currentQuestion.task}
								</span>
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-green-100 text-green-800">
									{currentQuestion.difficulty}
								</span>
							</div>
							<button
								on:click={handleFlag}
								class="px-4 py-2 rounded-lg font-medium transition-colors {flaggedQuestions.has(
									currentQuestion.id
								)
									? 'bg-red-100 text-red-700 hover:bg-red-200'
									: 'bg-gray-100 text-gray-700 hover:bg-gray-200'}"
							>
								{flaggedQuestions.has(currentQuestion.id) ? '🚩 Flagged' : 'Flag'}
							</button>
						</div>

						<!-- Question Text -->
						<div class="mb-6">
							<h2 class="text-xl font-semibold mb-4">
								{currentQuestion.question}
							</h2>
						</div>

						<!-- Options -->
						<div class="space-y-3 mb-6">
							{#each currentQuestion.options as option}
								{@const isSelected = selectedOptionId === option.id}
								{@const showCorrect = showExplanation && option.isCorrect}
								{@const showIncorrect =
									showExplanation && isSelected && !option.isCorrect}

								<button
									on:click={() => {
										if (!showExplanation) selectedOptionId = option.id;
									}}
									disabled={showExplanation}
									class="w-full text-left p-4 rounded-lg border-2 transition-all {showCorrect
										? 'border-green-500 bg-green-50'
										: showIncorrect
											? 'border-red-500 bg-red-50'
											: isSelected
												? 'border-indigo-500 bg-indigo-50'
												: 'border-gray-200 hover:border-indigo-300'} {showExplanation
										? 'cursor-not-allowed'
										: 'cursor-pointer'}"
								>
									<div class="flex items-center gap-3">
										<div
											class="w-5 h-5 rounded-full border-2 flex items-center justify-center {showCorrect
												? 'border-green-500 bg-green-500'
												: showIncorrect
													? 'border-red-500 bg-red-500'
													: isSelected
														? 'border-indigo-500 bg-indigo-500'
														: 'border-gray-300'}"
										>
											{#if isSelected && !showExplanation}
												<div class="w-2 h-2 rounded-full bg-white"></div>
											{/if}
											{#if showCorrect}
												<span class="text-white text-xs">✓</span>
											{/if}
											{#if showIncorrect}
												<span class="text-white text-xs">✗</span>
											{/if}
										</div>
										<span class="flex-1">{option.text}</span>
									</div>
								</button>
							{/each}
						</div>

						<!-- Explanation -->
						{#if showExplanation}
							<div class="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
								<h3 class="font-semibold mb-2">Explanation</h3>
								<p class="text-sm text-gray-700">{currentQuestion.explanation}</p>
							</div>
						{/if}

						<!-- Action Buttons -->
						<div class="flex justify-between">
							<button
								on:click={handlePrevious}
								disabled={currentIndex === 0}
								class="px-6 py-2 rounded-lg font-medium bg-gray-200 hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed transition"
							>
								Previous
							</button>
							<div class="flex gap-2">
								{#if !showExplanation}
									<button
										on:click={handleSubmitAnswer}
										disabled={!selectedOptionId || submitting}
										class="px-6 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
									>
										{submitting ? 'Submitting...' : 'Submit Answer'}
									</button>
								{:else}
									{#if isLastQuestion}
										<button
											on:click={handleCompleteSession}
											class="px-6 py-2 rounded-lg font-medium bg-green-600 text-white hover:bg-green-700 transition"
										>
											Complete Session
										</button>
									{:else}
										<button
											on:click={handleNext}
											class="px-6 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 transition"
										>
											Next Question
										</button>
									{/if}
								{/if}
							</div>
						</div>
					</div>
				</div>

				<!-- Sidebar -->
				<div class="space-y-6">
					<!-- Streak Counter -->
					{#if streak}
						<div class="bg-white rounded-lg shadow p-6">
							<h3 class="font-semibold mb-4">Current Streak</h3>
							<div class="text-center">
								<p class="text-4xl font-bold text-indigo-600">
									{streak.currentStreak}
								</p>
								<p class="text-sm text-gray-600 mt-1">consecutive correct</p>
							</div>
							<div class="mt-4 pt-4 border-t border-gray-200">
								<div class="flex justify-between text-sm">
									<span class="text-gray-600">Best Streak</span>
									<span class="font-medium">{streak.longestStreak}</span>
								</div>
								<div class="flex justify-between text-sm mt-2">
									<span class="text-gray-600">Total Answered</span>
									<span class="font-medium">{streak.totalAnswered}</span>
								</div>
								<div class="flex justify-between text-sm mt-2">
									<span class="text-gray-600">Accuracy</span>
									<span class="font-medium"
										>{streak.totalAnswered > 0
											? Math.round((streak.correctCount / streak.totalAnswered) * 100)
											: 0}%</span
									>
								</div>
							</div>
						</div>
					{/if}

					<!-- Question Navigator -->
					<div class="bg-white rounded-lg shadow p-6">
						<h3 class="font-semibold mb-4">Question Navigator</h3>
						<div class="grid grid-cols-5 gap-2">
							{#each Array(totalQuestions) as _, i}
								{@const isAnswered = answeredQuestions.has(
									questions[i]?.id
								)}
								{@const isCurrent = i === currentIndex}
								<button
									on:click={() => handleJumpToQuestion(i)}
									class="w-10 h-10 rounded text-sm font-medium transition-colors {isCurrent
										? 'bg-indigo-600 text-white'
										: isAnswered
											? 'bg-green-100 text-green-700'
											: 'bg-gray-100 text-gray-700 hover:bg-gray-200'}"
								>
									{i + 1}
								</button>
							{/each}
						</div>
					</div>
				</div>
			</div>
		</main>
	</div>
{/if}

// packages/web/src/app/practice/mock/session/[sessionId]/page.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useAuth } from '../../../../../contexts/AuthContext';
import { apiRequest } from '../../../../../lib/api';
import { PracticeQuestion } from '@pmp/shared';

interface SessionProgress {
  total: number;
  answered: number;
}

interface SessionData {
  sessionId: string;
  questions: (PracticeQuestion & { userAnswerId?: string })[];
  progress: SessionProgress;
  timeRemaining?: number; // Optional, if backend tracks it, otherwise we calculate
  totalTimeMinutes?: number;
}

export default function MockExamSessionPage() {
  const { sessionId } = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<SessionData | null>(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedOptionId, setSelectedOptionId] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Exam specific state
  const [timeLeft, setTimeLeft] = useState<number>(0); // in seconds
  const [showReview, setShowReview] = useState(false);
  const [examComplete, setExamComplete] = useState(false);

  const timerRef = useRef<NodeJS.Timeout | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Initialize session
  useEffect(() => {
    async function fetchSession() {
      if (!sessionId) return;
      try {
        setLoading(true);
        const response = await apiRequest<SessionData>(`/practice/sessions/${sessionId}`);

        if (response.data) {
          setSession(response.data);

          // Logic to determine time left
          // Assuming 230 minutes for 180 questions (standard PMP) or scaled based on question count
          // For now, let's assume standard PMP timing of ~1.2 mins per question if not provided is safe default
          // But ideally backend provides start time or time remaining.
          // Using a default of 75 seconds per question for now if not explicit.
          const totalSeconds = response.data.questions.length * 75;
          setTimeLeft(totalSeconds);

          // Restore answer for first question if exists
          if (response.data.questions.length > 0) {
            const firstQ = response.data.questions[0];
            if (firstQ) {
              setSelectedOptionId(firstQ.userAnswerId || null);
            }
          }
        }
      } catch (error) {
        console.error('Failed to fetch session', error);
      } finally {
        setLoading(false);
      }
    }

    if (user) {
      fetchSession();
    }
  }, [sessionId, user]);

  // Timer Tick
  useEffect(() => {
    if (loading || examComplete || !session) return;

    timerRef.current = setInterval(() => {
      setTimeLeft(prev => {
        if (prev <= 1) {
          clearInterval(timerRef.current!);
          finishExam();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [loading, examComplete, session]);

  // Sync current selection when index changes
  useEffect(() => {
    if (session && session.questions[currentIndex]) {
      setSelectedOptionId(session.questions[currentIndex].userAnswerId || null);
    }
    if (scrollRef.current) {
      scrollRef.current.scrollTop = 0;
    }
  }, [currentIndex, session]);

  const handleOptionSelect = async (optionId: string) => {
    setSelectedOptionId(optionId);

    // Optimistically update local state
    setSession(prev => {
      if (!prev) return null;
      const updatedQuestions = [...prev.questions];
      const currentQ = updatedQuestions[currentIndex];

      if (!currentQ) return prev;
      // Only update if changed
      if (currentQ.userAnswerId === optionId) return prev;

      updatedQuestions[currentIndex] = { ...currentQ, userAnswerId: optionId };

      // Update progress count
      const newAnsweredCount = updatedQuestions.filter(q => q.userAnswerId).length;

      return {
        ...prev,
        questions: updatedQuestions,
        progress: { ...prev.progress, answered: newAnsweredCount },
      };
    });

    // Silently sync with backend
    // We don't wait for this to resolve to let user move fast
    // We assume success, or retries could be handled in a more robust queue system in future
    if (session && session.questions[currentIndex]) {
      try {
        await apiRequest(
          `/practice/sessions/${sessionId}/answers/${session.questions[currentIndex].id}`,
          {
            method: 'POST',
            body: {
              selectedOptionId: optionId,
              timeSpentMs: 0, // We could track per-question time but global timer is more important here
            },
          }
        );
      } catch (err) {
        console.error('Failed to sync answer', err);
      }
    }
  };

  const jumpToQuestion = (index: number) => {
    setCurrentIndex(index);
    setShowReview(false);
  };

  const handleNext = () => {
    if (!session) return;
    if (currentIndex < session.questions.length - 1) {
      setCurrentIndex(prev => prev + 1);
    } else {
      setShowReview(true);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex(prev => prev - 1);
    }
  };

  const finishExam = async () => {
    if (!sessionId) return;
    setIsSubmitting(true);
    try {
      await apiRequest(`/practice/sessions/${sessionId}/complete`, { method: 'POST' });
      setExamComplete(true);
      router.push('/dashboard'); // Or a results page
    } catch (error) {
      console.error('Failed to complete exam', error);
      setIsSubmitting(false);
    }
  };

  const formatTime = (seconds: number) => {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = seconds % 60;
    return `${h > 0 ? h + ':' : ''}${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  if (!session) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 text-center text-white">
        Session not found.{' '}
        <button onClick={() => router.push('/practice')} className="text-primary-400 underline">
          Back
        </button>
      </div>
    );
  }

  const currentQuestion = session.questions[currentIndex];
  // Safe guard access
  if (!currentQuestion) return <div>Loading...</div>;

  const answeredCount = session.progress.answered;
  const totalCount = session.questions.length;
  const progressPercent = Math.round((answeredCount / totalCount) * 100);

  // Review Screen
  if (showReview) {
    return (
      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-white">Review Your Answers</h1>
          <div className="text-xl font-mono text-primary-400">{formatTime(timeLeft)}</div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 mb-6">
          <div className="grid grid-cols-5 sm:grid-cols-8 md:grid-cols-10 gap-3">
            {session.questions.map((q, idx) => (
              <button
                key={q.id}
                onClick={() => jumpToQuestion(idx)}
                className={`p-2 rounded text-sm font-medium border transition-colors ${
                  q.userAnswerId
                    ? 'bg-primary-900/40 border-primary-600 text-white'
                    : 'bg-gray-800 border-gray-700 text-gray-400 hover:border-gray-500'
                }`}
              >
                {idx + 1}
              </button>
            ))}
          </div>
        </div>

        <div className="flex justify-between">
          <button
            onClick={() => setShowReview(false)}
            className="px-6 py-3 bg-gray-800 text-white rounded-lg hover:bg-gray-700 transition"
          >
            Return to Exam
          </button>
          <button
            onClick={finishExam}
            disabled={isSubmitting}
            className="px-8 py-3 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition shadow-lg"
          >
            {isSubmitting ? 'Submitting...' : 'Submit Exam'}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-6 flex flex-col h-[calc(100vh-64px)]">
      {/* Header Bar */}
      <div className="flex items-center justify-between mb-6 bg-gray-900/50 p-4 rounded-xl border border-gray-800">
        <div className="flex items-center space-x-4">
          <span className="text-gray-400 font-medium">
            Question {currentIndex + 1} <span className="text-gray-600">/ {totalCount}</span>
          </span>
          <div className="h-4 w-32 bg-gray-800 rounded-full overflow-hidden hidden sm:block">
            <div
              className="h-full bg-primary-600 transition-all duration-500"
              style={{ width: `${progressPercent}%` }}
            ></div>
          </div>
        </div>

        <div className="flex items-center space-x-6">
          <div className="text-2xl font-mono font-bold text-primary-400 tracking-wider bg-gray-900 px-4 py-1 rounded-lg border border-gray-800 shadow-inner">
            {formatTime(timeLeft)}
          </div>
          <button
            onClick={() => setShowReview(true)}
            className="text-sm text-gray-400 hover:text-white underline"
          >
            Review All
          </button>
        </div>
      </div>

      <div className="flex-1 flex gap-6 overflow-hidden">
        {/* Main Question Area */}
        <div className="flex-1 flex flex-col overflow-y-auto pr-2 custom-scrollbar" ref={scrollRef}>
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-8 mb-6 shadow-sm">
            <p className="text-xl md:text-2xl text-white font-medium mb-8 leading-relaxed">
              {currentQuestion.questionText}
            </p>

            <div className="space-y-3">
              {currentQuestion.options.map(option => {
                const isSelected = selectedOptionId === option.id;
                return (
                  <button
                    key={option.id}
                    onClick={() => handleOptionSelect(option.id)}
                    className={`w-full text-left p-4 rounded-lg border-2 transition-all duration-200 flex items-start group ${
                      isSelected
                        ? 'bg-primary-900/20 border-primary-500 shadow-[0_0_15px_rgba(59,130,246,0.1)]'
                        : 'bg-gray-800/50 border-gray-700 hover:bg-gray-800 hover:border-gray-500'
                    }`}
                  >
                    <div
                      className={`mt-0.5 w-6 h-6 rounded-full border flex items-center justify-center mr-4 flex-shrink-0 transition-colors ${
                        isSelected
                          ? 'border-primary-500 bg-primary-500'
                          : 'border-gray-600 group-hover:border-gray-500'
                      }`}
                    >
                      {isSelected && <div className="w-2.5 h-2.5 bg-white rounded-full"></div>}
                    </div>
                    <span className={`text-lg ${isSelected ? 'text-white' : 'text-gray-300'}`}>
                      {option.text}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Side Navigation (Desktop) */}
        <div className="w-20 hidden lg:flex flex-col gap-2 overflow-y-auto custom-scrollbar bg-gray-900/30 p-2 rounded-xl border border-gray-800/50">
          {session.questions.map((q, idx) => {
            const isActive = idx === currentIndex;
            const isAnswered = !!q.userAnswerId;

            return (
              <button
                key={q.id}
                onClick={() => setCurrentIndex(idx)}
                className={`w-full aspect-square rounded flex items-center justify-center text-sm font-bold transition-all ${
                  isActive
                    ? 'bg-primary-600 text-white shadow-lg scale-105'
                    : isAnswered
                      ? 'bg-primary-900/30 text-primary-400 border border-primary-900'
                      : 'bg-gray-800 text-gray-500 hover:bg-gray-700'
                }`}
              >
                {idx + 1}
              </button>
            );
          })}
        </div>
      </div>

      {/* Footer Controls */}
      <div className="border-t border-gray-800 pt-6 mt-2 flex justify-between items-center bg-background py-4">
        <button
          onClick={handlePrev}
          disabled={currentIndex === 0}
          className={`px-6 py-2.5 rounded-lg border font-medium transition ${
            currentIndex === 0
              ? 'border-gray-800 text-gray-600 cursor-not-allowed'
              : 'border-gray-700 text-gray-300 hover:bg-gray-800 hover:text-white'
          }`}
        >
          &larr; Previous
        </button>

        <div className="flex gap-4">
          <button
            onClick={() => {
              // Flag logic could go here
            }}
            className="px-4 py-2.5 text-gray-400 hover:text-yellow-400 transition"
          >
            Flag for Review
          </button>
        </div>

        <button
          onClick={handleNext}
          className="px-8 py-2.5 bg-primary-600 text-white rounded-lg font-medium hover:bg-primary-700 transition shadow-lg hover:shadow-primary-900/20 flex items-center"
        >
          {currentIndex === totalCount - 1 ? 'Review Exam' : 'Next Question'}
          <span className="ml-2">&rarr;</span>
        </button>
      </div>
    </div>
  );
}
