// packages/web/src/app/flashcards/page.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { apiRequest } from "@/lib/api";
import { useToast } from "@/components/ToastProvider";
import { useRequireAuth } from "@/hooks/useRequireAuth";
import { FullPageSkeleton } from "@/components/FullPageSkeleton";
import type { Domain } from "@/data/pmpExamContent";

interface FlashcardStats {
  mastered: number;
  learning: number;
  dueForReview: number;
  totalCards: number;
}

export default function FlashcardsPage() {
  const router = useRouter();
  const { canAccess, isLoading: authLoading } = useRequireAuth();
  const toast = useToast();
  const [stats, setStats] = useState<FlashcardStats | null>(null);
  const [domains, setDomains] = useState<Domain[]>([]);
  const [loading, setLoading] = useState(true);
  const [starting, setStarting] = useState<"review" | "all" | "focused" | null>(
    null,
  );

  // Selection state for focused mode
  const [selectedDomainId, setSelectedDomainId] = useState<string | null>(null);
  const [selectedTaskId, setSelectedTaskId] = useState<string | null>(null);
  const [cardCount, setCardCount] = useState<number>(20);
  const [showFilters, setShowFilters] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      const statsRes = await apiRequest<{ stats: FlashcardStats }>(
        "/flashcards/stats",
      );
      setStats(statsRes.data?.stats ?? null);

      // Fetch domains for selection
      const domainsRes = await apiRequest<{ domains: Domain[] }>("/domains");
      setDomains(domainsRes.data?.domains ?? []);
    } catch (error) {
      console.error("Failed to fetch flashcard data:", error);
      toast.error("Failed to load flashcards. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    if (canAccess) {
      fetchData();
    }
  }, [canAccess, fetchData]);

  const getFilteredDomainTasks = useCallback(() => {
    if (!selectedDomainId) return [];
    const domain = domains.find((d) => d.id === selectedDomainId);
    return domain?.tasks || [];
  }, [domains, selectedDomainId]);

  const startSession = async (mode: "review" | "all" | "focused") => {
    try {
      setStarting(mode);

      let options: Record<string, unknown> = { cardCount };

      if (mode === "review") {
        options = { ...options, prioritizeReview: true };
      }

      if (mode === "focused") {
        if (!selectedDomainId) {
          toast.error("Please select a domain");
          setStarting(null);
          return;
        }
        options = {
          ...options,
          domainIds: [selectedDomainId],
          taskIds: selectedTaskId ? [selectedTaskId] : undefined,
          prioritizeReview: false,
        };
      }

      const response = await apiRequest<{ sessionId: string }>(
        "/flashcards/sessions",
        {
          method: "POST",
          body: options,
        },
      );
      const sessionId = response.data?.sessionId;
      if (sessionId) {
        router.push(`/flashcards/session/${sessionId}`);
      }
    } catch (error) {
      console.error("Failed to start session:", error);
      toast.error("Failed to start session. Please try again.");
    } finally {
      setStarting(null);
    }
  };

  const resetFilters = useCallback(() => {
    setSelectedDomainId(null);
    setSelectedTaskId(null);
    setCardCount(20);
    setShowFilters(false);
  }, []);

  const selectedDomain = domains.find((d) => d.id === selectedDomainId);
  const tasksForSelectedDomain = getFilteredDomainTasks();
  const hasActiveFilters =
    selectedDomainId !== null || selectedTaskId !== null || cardCount !== 20;

  if (authLoading || loading) {
    return <FullPageSkeleton />;
  }

  // CRITICAL-007: Use dueForReview from stats instead of capped array length
  const dueCardsCount = stats?.dueForReview || 0;

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Organic Blur Shapes */}
      <div className="blur-shape bg-md-primary w-96 h-96 top-0 left-0 -translate-x-1/2 -translate-y-1/2"></div>
      <div className="blur-shape bg-md-tertiary w-96 h-96 bottom-0 right-0 translate-x-1/2 translate-y-1/2"></div>

      <Navbar />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 relative z-10">
        <div className="mb-12 text-center">
          <h1 className="text-4xl font-bold mb-4 text-md-on-background">
            Flashcards
          </h1>
          <p className="text-xl text-md-on-surface-variant max-w-2xl mx-auto">
            Master key concepts with spaced repetition learning.
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <div className="card text-center hover:scale-105 transition-transform duration-300">
            <p className="text-4xl font-bold text-md-primary mb-2">
              {stats?.mastered || 0}
            </p>
            <p className="text-sm font-medium text-md-on-surface-variant">
              Mastered
            </p>
          </div>
          <div className="card text-center hover:scale-105 transition-transform duration-300">
            <p className="text-4xl font-bold text-md-tertiary mb-2">
              {stats?.learning || 0}
            </p>
            <p className="text-sm font-medium text-md-on-surface-variant">
              Learning
            </p>
          </div>
          <div className="card text-center hover:scale-105 transition-transform duration-300">
            <p className="text-4xl font-bold text-md-error mb-2">
              {dueCardsCount}
            </p>
            <p className="text-sm font-medium text-md-on-surface-variant">
              Due Today
            </p>
          </div>
          <div className="card text-center hover:scale-105 transition-transform duration-300">
            <p className="text-4xl font-bold text-md-on-surface mb-2">
              {stats?.totalCards || 0}
            </p>
            <p className="text-sm font-medium text-md-on-surface-variant">
              Total Cards
            </p>
          </div>
        </div>

        {/* Action Cards */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {/* Review Due Cards */}
          <div className="card group hover:shadow-lg transition-all duration-300 border border-transparent hover:border-md-primary/20">
            <div className="w-14 h-14 rounded-2xl bg-md-primary-container text-md-on-primary-container flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
              <svg
                className="w-7 h-7"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <h2 className="text-xl font-bold mb-3 text-md-on-surface">
              Review Due Cards
            </h2>
            <p className="text-md-on-surface-variant mb-6 min-h-[3rem]">
              {dueCardsCount > 0
                ? `You have ${dueCardsCount} cards due for review. Keep your streak going!`
                : "No cards due right now. Start a session to review any available cards!"}
            </p>
            <button
              onClick={() => startSession("review")}
              disabled={starting !== null}
              className="btn btn-primary w-full"
            >
              {starting === "review" ? "Starting..." : "Start Review"}
            </button>
          </div>

          {/* Study All Cards */}
          <div className="card group hover:shadow-lg transition-all duration-300 border border-transparent hover:border-md-secondary/20">
            <div className="w-14 h-14 rounded-2xl bg-md-secondary-container text-md-on-secondary-container flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
              <svg
                className="w-7 h-7"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
                />
              </svg>
            </div>
            <h2 className="text-xl font-bold mb-3 text-md-on-surface">
              Study Session
            </h2>
            <p className="text-md-on-surface-variant mb-6 min-h-[3rem]">
              Start a new study session with a mix of new and review cards.
            </p>
            <button
              onClick={() => startSession("all")}
              disabled={starting !== null}
              className="btn btn-secondary w-full"
            >
              {starting === "all" ? "Starting..." : "Start Session"}
            </button>
          </div>

          {/* Focus on Task */}
          <div
            className={`card group hover:shadow-lg transition-all duration-300 border ${hasActiveFilters ? "border-md-tertiary/50 bg-md-tertiary-container/10" : "border-transparent hover:border-md-tertiary/20"}`}
          >
            <div className="w-14 h-14 rounded-2xl bg-md-tertiary-container text-md-on-tertiary-container flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
              <svg
                className="w-7 h-7"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"
                />
              </svg>
            </div>
            <h2 className="text-xl font-bold mb-3 text-md-on-surface">
              Focus on Task
            </h2>
            <p className="text-md-on-surface-variant mb-6 min-h-[3rem]">
              {selectedDomain && selectedTaskId
                ? `Studying: ${selectedDomain.name} - ${tasksForSelectedDomain.find((t) => t.id === selectedTaskId)?.code}`
                : selectedDomain
                  ? `Domain selected: ${selectedDomain.name}`
                  : "Target specific domains and tasks for focused practice."}
            </p>
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`btn w-full justify-center ${hasActiveFilters ? "btn-tertiary" : "btn-outline"}`}
            >
              {showFilters ? "Hide Options" : "Select Focus"}
            </button>
          </div>

          {/* Create Custom */}
          <div className="card group hover:shadow-lg transition-all duration-300 border border-transparent hover:border-md-tertiary/20">
            <div className="w-14 h-14 rounded-2xl bg-md-tertiary-container text-md-on-tertiary-container flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
              <svg
                className="w-7 h-7"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 4v16m8-8H4"
                />
              </svg>
            </div>
            <h2 className="text-xl font-bold mb-3 text-md-on-surface">
              Create Custom Card
            </h2>
            <p className="text-md-on-surface-variant mb-6 min-h-[3rem]">
              Create your own flashcards for concepts you want to remember.
            </p>
            <Link
              href="/flashcards/create"
              className="btn btn-outline w-full justify-center"
            >
              Create Card
            </Link>
          </div>
        </div>

        {/* Filter Section */}
        {showFilters && (
          <div className="card mt-8 animate-slideUp bg-md-surface-container">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-lg font-bold text-md-on-surface">
                Session Options
              </h3>
              {hasActiveFilters && (
                <button
                  onClick={resetFilters}
                  className="text-sm text-md-primary hover:underline"
                >
                  Reset to Defaults
                </button>
              )}
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              {/* Domain Selection */}
              <div>
                <label
                  htmlFor="domain-select"
                  className="block text-sm font-medium text-md-on-surface-variant mb-2"
                >
                  Domain (optional)
                </label>
                <select
                  id="domain-select"
                  value={selectedDomainId || ""}
                  onChange={(e) => {
                    setSelectedDomainId(e.target.value || null);
                    setSelectedTaskId(null); // Reset task when domain changes
                  }}
                  className="input w-full"
                >
                  <option value="">All Domains</option>
                  {domains.map((domain) => (
                    <option key={domain.id} value={domain.id}>
                      {domain.code} - {domain.name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Task Selection */}
              <div>
                <label
                  htmlFor="task-select"
                  className="block text-sm font-medium text-md-on-surface-variant mb-2"
                >
                  Task (optional)
                </label>
                <select
                  id="task-select"
                  value={selectedTaskId || ""}
                  onChange={(e) => setSelectedTaskId(e.target.value || null)}
                  disabled={!selectedDomainId}
                  className="input w-full disabled:opacity-50"
                >
                  <option value="">All Tasks in Domain</option>
                  {tasksForSelectedDomain.map((task) => (
                    <option key={task.id} value={task.id}>
                      {task.code} - {task.name.substring(0, 30)}...
                    </option>
                  ))}
                </select>
              </div>

              {/* Card Count */}
              <div>
                <label
                  htmlFor="card-count"
                  className="block text-sm font-medium text-md-on-surface-variant mb-2"
                >
                  Number of Cards
                </label>
                <select
                  id="card-count"
                  value={cardCount}
                  onChange={(e) => setCardCount(Number(e.target.value))}
                  className="input w-full"
                >
                  <option value={10}>10 cards</option>
                  <option value={20}>20 cards</option>
                  <option value={30}>30 cards</option>
                  <option value={50}>50 cards</option>
                </select>
              </div>

              {/* Start Button */}
              <div className="flex items-end">
                <button
                  onClick={() => startSession("focused")}
                  disabled={starting !== null || !selectedDomainId}
                  className="btn btn-tertiary w-full"
                >
                  {starting === "focused"
                    ? "Starting..."
                    : "Start Focused Session"}
                </button>
              </div>
            </div>

            {/* Preview Info */}
            {selectedDomainId && (
              <div className="mt-4 p-3 bg-md-surface-container-low rounded-lg">
                <p className="text-sm text-md-on-surface-variant">
                  {selectedTaskId
                    ? `This will show flashcards specifically for the "${selectedDomain?.name}" domain and task "${tasksForSelectedDomain.find((t) => t.id === selectedTaskId)?.name}".`
                    : `This will show flashcards for the "${selectedDomain?.name}" domain across all its tasks.`}
                </p>
              </div>
            )}
          </div>
        )}

        {/* How it works */}
        <div className="card mt-12 bg-md-surface-container-low border-none">
          <h2 className="text-xl font-bold mb-8 text-center text-md-on-surface">
            How Spaced Repetition Works
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center group">
              <div className="w-16 h-16 rounded-full bg-md-primary/10 text-md-primary flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform duration-300">
                <span className="text-2xl font-bold">1</span>
              </div>
              <p className="font-bold text-lg mb-2 text-md-on-surface">
                Know It
              </p>
              <p className="text-md-on-surface-variant">
                Cards you know well are shown less frequently.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-16 h-16 rounded-full bg-md-secondary/10 text-md-secondary flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform duration-300">
                <span className="text-2xl font-bold">2</span>
              </div>
              <p className="font-bold text-lg mb-2 text-md-on-surface">
                Learning
              </p>
              <p className="text-md-on-surface-variant">
                Cards you{"'"}re learning are shown more often.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-16 h-16 rounded-full bg-md-tertiary/10 text-md-tertiary flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform duration-300">
                <span className="text-2xl font-bold">3</span>
              </div>
              <p className="font-bold text-lg mb-2 text-md-on-surface">
                Don{"'"}t Know
              </p>
              <p className="text-md-on-surface-variant">
                Cards you don{"'"}t know are shown again soon.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

// packages/web-svelte/src/routes/flashcards/+page.svelte
<script lang="ts">
 import { onMount } from 'svelte';
 import LoadingState from "$lib/components/LoadingState.svelte";
 import ErrorState from "$lib/components/ErrorState.svelte";
 import ECOBadge from "$lib/components/ECOBadge.svelte";
 import {
 getMasteredCount,
 getRecentReviews,
 type FlashcardReview
 } from "$lib/utils/flashcardStorage";
 import {
 getQuickStats,
 getFlashcardsByDomain,
 prefetchDomains,
 type Flashcard,
 type DomainManifest
 } from "$lib/utils/flashcardsData";
 import { goto } from '$app/navigation';
 import { base } from '$app/paths';
 import Card from '$lib/components/ui/Card.svelte';

 // Domain filter options
 interface DomainFilter {
 id: string;
 label: string;
 color: string;
 }

 const DOMAIN_FILTERS: DomainFilter[] = [
 { id: 'all', label: 'All', color: 'gray' },
 { id: 'people', label: 'People', color: 'blue' },
 { id: 'process', label: 'Process', color: 'green' },
 { id: 'business', label: 'Business Environment', color: 'purple' }
 ];

 // Local storage state
 let localMasteredCount = $state(0);
 let recentReviews: FlashcardReview[] = $state([]);
 let showRecentReviews = $state(false);

 // Data loading state
 let loading = $state(true);
 let allFlashcards: Flashcard[] = $state([]);
 let quickStats: { totalFlashcards: number; totalDomains: number; totalTasks: number; domains: DomainManifest[] } | null = $state(null);
 let error: string | null = $state(null);

 // Debounced search removed

 // Format date helper
 function formatReviewDate(timestamp: string): string {
 const date = new Date(timestamp);
 const now = new Date();
 const diffMs = now.getTime() - date.getTime();
 const diffMins = Math.floor(diffMs / 60000);
 const diffHours = Math.floor(diffMs / 3600000);
 const diffDays = Math.floor(diffMs / 86400000);

 if (diffMins < 60) return `${diffMins}m ago`;
 if (diffHours < 24) return `${diffHours}h ago`;
 if (diffDays < 7) return `${diffDays}d ago`;
 return date.toLocaleDateString();
 }

 // Get rating color
 function getRatingColor(rating: string): string {
 switch (rating) {
 case 'know_it':
 return 'bg-green-100 text-green-800 border-green-200';
 case 'learning':
 return 'bg-yellow-100 text-yellow-800 border-yellow-200';
 case 'dont_know':
 return 'bg-red-100 text-red-800 border-red-200';
 default:
 return 'bg-gray-100 text-gray-800 border-gray-200';
 }
 }

 // Get rating label
 function getRatingLabel(rating: string): string {
 switch (rating) {
 case 'know_it':
 return 'Know It';
 case 'learning':
 return 'Learning';
 case 'dont_know':
 return "Don't Know";
 default:
 return rating;
 }
 }

 // Pagination helpers removed

 onMount(async () => {
 // Load data from localStorage first (fast, synchronous)
 localMasteredCount = getMasteredCount();
 recentReviews = getRecentReviews();

 try {
 // FAST: Load only the manifest (~500 bytes) initially
 quickStats = await getQuickStats();
 
 // Immediately mark as loaded - page renders instantly with stats
 loading = false;
 
 // Load all cards for prefetching
 const domains = ['people', 'process', 'business'];
 const results = await Promise.all(domains.map(d => getFlashcardsByDomain(d)));
 allFlashcards = results.flat();
 
 // Start prefetching
 prefetchDomains('people');
 } catch (err) {
 console.error('Failed to load flashcards:', err);
 error = err instanceof Error ? err.message : 'Failed to load flashcards';
 loading = false;
 }
 });

 // Re-fetch progress when returning to the page (e.g. from practice)
 $effect(() => {
 // This will trigger whenever the component is active
 localMasteredCount = getMasteredCount();
 recentReviews = getRecentReviews();
 });

 // Domain filter effect removed
</script>

{#if loading}
 <LoadingState message="Loading flashcards..." />
{:else if error}
 <ErrorState
 title="Flashcards Error"
 message={error}
 />
{:else}
 <div class="relative min-h-screen overflow-hidden bg-background">
 <!-- Organic Blob Backgrounds -->
 <div class="absolute -top-20 -left-20 w-96 h-96 bg-primary/20 rounded-blob blur-3xl animate-float opacity-70"></div>
 <div class="absolute top-40 -right-20 w-80 h-80 bg-secondary/15 rounded-blob blur-3xl animate-float delay-1000 opacity-60"></div>
 <div class="absolute bottom-0 left-1/3 w-full h-96 bg-accent/30 rounded-t-[50%] blur-3xl opacity-40"></div>

 <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
 <!-- ECO Badge -->
 <div class="mb-6">
 <ECOBadge variant="compact" />
 </div>

 <h1 class="text-3xl md:text-4xl font-bold font-serif text-foreground mb-6">Flashcards</h1>

 <!-- Session selection is now via the practice session grid below -->

 <!-- Practice Sessions -->
 <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
 {#each [25, 50, 75, 100] as limit}
 <a
 href="{base}/flashcards/practice?limit={limit}"
 class="group block"
 aria-label="Practice {limit} flashcards"
 >
 <Card class="p-6 h-full transition-all hover:scale-[1.03] hover:shadow-hover">
 <div class="flex items-center justify-between mb-4">
 <div class="p-3 bg-primary/10 rounded-xl text-primary group-hover:scale-110 transition-transform duration-300">
 <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
 <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
 </svg>
 </div>
 <span class="text-xs font-bold text-primary bg-primary/10 px-2 py-1 rounded-lg">SRS</span>
 </div>
 <h3 class="text-xl font-bold text-foreground mb-1">Practice {limit}</h3>
 <p class="text-sm text-muted-foreground">Random {limit} cards from your SRS queue</p>
 </Card>
 </a>
 {/each}
 </div>

 <!-- Recent Reviews -->
 {#if recentReviews && recentReviews.length > 0}
 <Card class="mb-8">
 <div class="px-6 py-4 border-b border-border flex items-center justify-between">
 <h2 class="text-lg font-medium text-foreground">
 Recent Reviews ({recentReviews.length})
 </h2>
 <button
 onclick={() => showRecentReviews = !showRecentReviews}
 class="text-sm text-primary hover:text-primary/80 hover:scale-105 transition-all duration-300"
 aria-expanded={showRecentReviews}
 >
 {showRecentReviews ? 'Hide' : 'Show'}
 </button>
 </div>

 {#if showRecentReviews}
 <div class="divide-y divide-border">
 {#each recentReviews as review}
 <div class="px-6 py-3 hover:bg-muted/50 transition-colors duration-300">
 <div class="flex items-start justify-between gap-4">
 <div class="flex-1 min-w-0">
 <p class="text-sm font-medium text-foreground truncate">
 {review.cardFront}
 </p>
 <p class="text-xs text-muted-foreground mt-1">
 {formatReviewDate(review.timestamp)}
 </p>
 </div>
 <span
 class="px-3 py-1 text-xs font-medium rounded-full border flex-shrink-0 {getRatingColor(review.rating)}"
 >
 {getRatingLabel(review.rating)}
 </span>
 </div>
 </div>
 {/each}
 </div>
 {/if}
 </Card>
 {/if}

 <!-- Quick Stats -->
 {#if quickStats}
 <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
 <Card class="p-6 cursor-default">
 <h2 class="text-lg font-medium text-foreground mb-2">Total Cards</h2>
 <p class="text-3xl font-bold text-primary">{quickStats.totalFlashcards || 0}</p>
 </Card>
 <Card class="p-6 cursor-default">
 <h2 class="text-lg font-medium text-foreground mb-2">Mastered</h2>
 <p class="text-3xl font-bold text-secondary">{localMasteredCount || 0}</p>
 </Card>
 </div>
 {/if}
 </div>
 </div>
{/if}
