// packages/web/src/app/flashcards/session/[sessionId]/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useAuth } from '../../../../contexts/AuthContext';
import { apiRequest } from '../../../../lib/api';
import { Flashcard, FlashcardRating } from '@pmp/shared';

interface SessionData {
  sessionId: string;
  cards: Flashcard[];
  progress: {
    total: number;
    answered: number;
  };
}

export default function FlashcardSessionPage() {
  const { sessionId } = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<SessionData | null>(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [sessionComplete, setSessionComplete] = useState(false);
  const [startTime, setStartTime] = useState<number>(Date.now());

  useEffect(() => {
    async function fetchSession() {
      if (!sessionId) return;
      try {
        setLoading(true);
        const response = await apiRequest<SessionData>(`/flashcards/sessions/${sessionId}`);
        if (response.data) {
          setSession(response.data);

          // Resume from first unanswered card if possible, or 0
          // Since API doesn't filter answered yet in my quick implementation,
          // we start at 0 or saved progress index if passed.
          // For now, start at 0.
          setCurrentIndex(response.data.progress.answered);
          if (
            response.data.progress.answered >= response.data.progress.total &&
            response.data.progress.total > 0
          ) {
            setSessionComplete(true);
          }
        }
      } catch (error) {
        console.error('Failed to fetch session', error);
      } finally {
        setLoading(false);
      }
    }

    if (user) {
      fetchSession();
    }
  }, [sessionId, user]);

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  const handleRate = async (rating: FlashcardRating) => {
    if (!session || !sessionId) return;

    const currentCard = session.cards[currentIndex];
    if (!currentCard) return;

    const timeSpentMs = Date.now() - startTime;

    try {
      await apiRequest(`/flashcards/sessions/${sessionId}/responses/${currentCard.id}`, {
        method: 'POST',
        body: {
          rating,
          timeSpentMs,
        },
      });

      // Move to next card
      if (currentIndex < session.cards.length - 1) {
        setIsFlipped(false);
        setCurrentIndex(prev => prev + 1);
        setStartTime(Date.now());
      } else {
        // Session complete
        await completeSession();
      }
    } catch (error) {
      console.error('Failed to record response', error);
    }
  };

  const completeSession = async () => {
    try {
      await apiRequest(`/flashcards/sessions/${sessionId}/complete`, { method: 'POST' });
      setSessionComplete(true);
    } catch (error) {
      console.error('Failed to complete session', error);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  if (!session) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 text-center bg-gray-900 border border-gray-800 rounded-lg">
        <h1 className="text-2xl font-bold text-white mb-2">Session Not Found</h1>
        <button
          onClick={() => router.push('/flashcards')}
          className="px-4 py-2 bg-primary-600 text-white rounded hover:bg-primary-700 transition"
        >
          Back to Flashcards
        </button>
      </div>
    );
  }

  if (sessionComplete) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16 text-center">
        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8 shadow-xl">
          <div className="text-6xl mb-4">🎉</div>
          <h1 className="text-3xl font-bold text-white mb-4">Session Complete!</h1>
          <p className="text-gray-400 mb-8">
            Great job! You've reviewed {session.cards.length} cards.
          </p>
          <div className="flex justify-center space-x-4">
            <button
              onClick={() => router.push('/flashcards')}
              className="px-6 py-3 bg-gray-800 text-white rounded-lg hover:bg-gray-700 transition"
            >
              Back to Overview
            </button>
            <button
              onClick={() => router.push('/dashboard')}
              className="px-6 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition"
            >
              Go to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  const currentCard = session.cards[currentIndex];
  const progress =
    session.cards.length > 0 ? Math.round((currentIndex / session.cards.length) * 100) : 0;

  if (!currentCard) {
    return <div>Loading card...</div>;
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 min-h-[80vh] flex flex-col">
      {/* Header / Progress */}
      <div className="mb-8 flex items-center justify-between">
        <button
          onClick={() => router.push('/flashcards')}
          className="text-gray-400 hover:text-white transition"
        >
          &larr; Exit
        </button>
        <div className="flex-1 mx-8">
          <div className="flex justify-between text-xs text-gray-400 mb-1">
            <span>
              Card {currentIndex + 1} of {session.cards.length}
            </span>
            <span>{Math.round(progress)}%</span>
          </div>
          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-primary-500 transition-all duration-300"
              style={{ width: `${progress}%` }}
            ></div>
          </div>
        </div>
        <div className="w-10"></div> {/* Spacer for balance */}
      </div>

      {/* Card Area */}
      <div className="flex-1 flex flex-col items-center justify-center mb-8">
        <div
          className="w-full max-w-2xl aspect-[3/2] perspective-1000 cursor-pointer group"
          onClick={handleFlip}
        >
          <div
            className={`relative w-full h-full duration-500 transform-style-3d transition-transform ${isFlipped ? 'rotate-y-180' : ''}`}
          >
            {/* Front */}
            <div className="absolute w-full h-full backface-hidden bg-gray-800 border-2 border-gray-700 rounded-2xl p-8 flex flex-col items-center justify-center text-center shadow-lg group-hover:border-primary-500/50 transition-colors">
              <span className="text-gray-500 text-sm uppercase tracking-wider mb-4">Question</span>
              <h2 className="text-2xl md:text-3xl font-medium text-white">{currentCard.front}</h2>
              <div className="absolute bottom-4 text-gray-500 text-xs">Click to flip</div>
            </div>

            {/* Back */}
            <div className="absolute w-full h-full backface-hidden bg-gray-800 border-2 border-primary-900 rounded-2xl p-8 flex flex-col items-center justify-center text-center shadow-lg rotate-y-180">
              <span className="text-primary-400 text-sm uppercase tracking-wider mb-4">Answer</span>
              <p className="text-xl md:text-2xl text-gray-100 leading-relaxed">
                {currentCard.back}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Controls */}
      <div className="h-24">
        {isFlipped ? (
          <div className="grid grid-cols-3 gap-4 max-w-2xl mx-auto w-full">
            <button
              onClick={() => handleRate('dont_know')}
              className="py-4 bg-red-900/30 border border-red-800 text-red-200 rounded-xl hover:bg-red-900/50 transition"
            >
              <div className="font-bold mb-1">Again</div>
              <div className="text-xs opacity-70">&lt; 1 min</div>
            </button>
            <button
              onClick={() => handleRate('learning')}
              className="py-4 bg-yellow-900/30 border border-yellow-800 text-yellow-200 rounded-xl hover:bg-yellow-900/50 transition"
            >
              <div className="font-bold mb-1">Hard</div>
              <div className="text-xs opacity-70">2 days</div>
            </button>
            <button
              onClick={() => handleRate('know_it')}
              className="py-4 bg-green-900/30 border border-green-800 text-green-200 rounded-xl hover:bg-green-900/50 transition"
            >
              <div className="font-bold mb-1">Easy</div>
              <div className="text-xs opacity-70">4 days</div>
            </button>
          </div>
        ) : (
          <div className="flex justify-center">
            <button
              onClick={handleFlip}
              className="px-8 py-3 bg-gray-700 text-white rounded-full hover:bg-gray-600 transition shadow-lg font-medium"
            >
              Show Answer
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// packages/web-svelte/src/routes/practice/[sessionId]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { practiceApi } from '$lib/utils/api';
	import LoadingState from '$lib/components/LoadingState.svelte';
	import ErrorState from '$lib/components/ErrorState.svelte';

	export let data;

	let loading = true;
	let questions = [];
	let currentIndex = 0;
	let selectedOptionId = null;
	let showExplanation = false;
	let submitting = false;
	let answeredQuestions = new Set();
	let flaggedQuestions = new Set();
	let streak = null;
	let error = null;
	let totalQuestions = 0;

	onMount(() => {
		// Use data from load function if available
		if (data.questions) {
			questions = data.questions;
		}
		if (data.totalQuestions !== undefined) {
			totalQuestions = data.totalQuestions;
		}
		if (data.streak) {
			streak = data.streak;
		}
		if (data.error) {
			error = data.error;
		}
		loading = false;
	});

	async function handleSubmitAnswer() {
		if (!selectedOptionId || submitting) return;

		submitting = true;
		const question = questions[currentIndex];
		if (!question) {
			submitting = false;
			return;
		}

		try {
			const sessionId = $page.params.sessionId;
			await practiceApi.submitAnswer({
				sessionId,
				questionId: question.id,
				selectedOptionId,
				timeSpentMs: 0
			});

			answeredQuestions = new Set([...answeredQuestions, question.id]);
			showExplanation = true;
		} catch (err) {
			console.error('Failed to submit answer:', err);
			error = err instanceof Error ? err.message : 'Failed to submit answer';
		} finally {
			submitting = false;
		}
	}

	function handleNext() {
		if (currentIndex < questions.length - 1) {
			currentIndex += 1;
			selectedOptionId = null;
			showExplanation = false;
		}
	}

	function handlePrevious() {
		if (currentIndex > 0) {
			currentIndex -= 1;
			selectedOptionId = null;
			showExplanation = false;
		}
	}

	function handleJumpToQuestion(index) {
		currentIndex = index;
		selectedOptionId = null;
		showExplanation = false;
	}

	async function handleFlag() {
		const question = questions[currentIndex];
		if (!question) return;

		const isFlagged = flaggedQuestions.has(question.id);

		try {
			if (isFlagged) {
				await practiceApi.unflagQuestion(question.id);
				flaggedQuestions = new Set(
					Array.from(flaggedQuestions).filter((id) => id !== question.id)
				);
			} else {
				await practiceApi.flagQuestion(question.id);
				flaggedQuestions = new Set([...flaggedQuestions, question.id]);
			}
		} catch (err) {
			console.error('Failed to flag question:', err);
		}
	}

	async function handleCompleteSession() {
		try {
			const sessionId = $page.params.sessionId;
			await practiceApi.completeSession(sessionId);
			goto('/dashboard');
		} catch (err) {
			console.error('Failed to complete session:', err);
			error = err instanceof Error ? err.message : 'Failed to complete session';
		}
	}

	$: currentQuestion = questions[currentIndex];
	$: progress = totalQuestions > 0 ? ((currentIndex + 1) / totalQuestions) * 100 : 0;
	$: isLastQuestion = currentIndex === totalQuestions - 1;
</script>

{#if loading}
	<LoadingState message="Loading practice session..." />
{:else if error}
	<ErrorState title="Practice Session Error" message={error} />
{:else if !currentQuestion}
	<ErrorState
		title="Question Not Found"
		message="Could not load the current question."
	/>
{:else}
	<div class="min-h-screen bg-gray-50">
		<nav class="bg-white border-b border-gray-200">
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
				<div class="flex justify-between h-16">
					<div class="flex items-center">
						<button
							on:click={() => window.history.back()}
							class="text-gray-700 hover:text-indigo-600"
						>
							← Back
						</button>
					</div>
				</div>
			</div>
		</nav>

		<main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
			<!-- Progress Bar -->
			<div class="mb-6">
				<div class="flex justify-between items-center mb-2">
					<span class="text-sm font-medium">
						Question {currentIndex + 1} of {totalQuestions}
					</span>
					<span class="text-sm font-medium">{Math.round(progress)}%</span>
				</div>
				<div class="w-full bg-gray-200 rounded-full h-2.5 overflow-hidden">
					<div
						class="bg-indigo-600 h-2.5 rounded-full transition-all duration-500 ease-out"
						style="width: {progress}%"
					></div>
				</div>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
				<!-- Main Question Area -->
				<div class="lg:col-span-2">
					<div class="bg-white rounded-lg shadow p-6">
						<!-- Question Header -->
						<div class="flex justify-between items-start mb-4">
							<div class="flex gap-2">
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-blue-100 text-blue-800">
									{currentQuestion.domain}
								</span>
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-purple-100 text-purple-800">
									{currentQuestion.task}
								</span>
								<span class="px-3 py-1 text-xs font-medium rounded-full bg-green-100 text-green-800">
									{currentQuestion.difficulty}
								</span>
							</div>
							<button
								on:click={handleFlag}
								class="px-4 py-2 rounded-lg font-medium transition-colors {flaggedQuestions.has(
									currentQuestion.id
								)
									? 'bg-red-100 text-red-700 hover:bg-red-200'
									: 'bg-gray-100 text-gray-700 hover:bg-gray-200'}"
							>
								{flaggedQuestions.has(currentQuestion.id) ? '🚩 Flagged' : 'Flag'}
							</button>
						</div>

						<!-- Question Text -->
						<div class="mb-6">
							<h2 class="text-xl font-semibold mb-4">
								{currentQuestion.question}
							</h2>
						</div>

						<!-- Options -->
						<div class="space-y-3 mb-6">
							{#each currentQuestion.options as option}
								{@const isSelected = selectedOptionId === option.id}
								{@const showCorrect = showExplanation && option.isCorrect}
								{@const showIncorrect =
									showExplanation && isSelected && !option.isCorrect}

								<button
									on:click={() => {
										if (!showExplanation) selectedOptionId = option.id;
									}}
									disabled={showExplanation}
									class="w-full text-left p-4 rounded-lg border-2 transition-all {showCorrect
										? 'border-green-500 bg-green-50'
										: showIncorrect
											? 'border-red-500 bg-red-50'
											: isSelected
												? 'border-indigo-500 bg-indigo-50'
												: 'border-gray-200 hover:border-indigo-300'} {showExplanation
										? 'cursor-not-allowed'
										: 'cursor-pointer'}"
								>
									<div class="flex items-center gap-3">
										<div
											class="w-5 h-5 rounded-full border-2 flex items-center justify-center {showCorrect
												? 'border-green-500 bg-green-500'
												: showIncorrect
													? 'border-red-500 bg-red-500'
													: isSelected
														? 'border-indigo-500 bg-indigo-500'
														: 'border-gray-300'}"
										>
											{#if isSelected && !showExplanation}
												<div class="w-2 h-2 rounded-full bg-white"></div>
											{/if}
											{#if showCorrect}
												<span class="text-white text-xs">✓</span>
											{/if}
											{#if showIncorrect}
												<span class="text-white text-xs">✗</span>
											{/if}
										</div>
										<span class="flex-1">{option.text}</span>
									</div>
								</button>
							{/each}
						</div>

						<!-- Explanation -->
						{#if showExplanation}
							<div class="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
								<h3 class="font-semibold mb-2">Explanation</h3>
								<p class="text-sm text-gray-700">{currentQuestion.explanation}</p>
							</div>
						{/if}

						<!-- Action Buttons -->
						<div class="flex justify-between">
							<button
								on:click={handlePrevious}
								disabled={currentIndex === 0}
								class="px-6 py-2 rounded-lg font-medium bg-gray-200 hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed transition"
							>
								Previous
							</button>
							<div class="flex gap-2">
								{#if !showExplanation}
									<button
										on:click={handleSubmitAnswer}
										disabled={!selectedOptionId || submitting}
										class="px-6 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
									>
										{submitting ? 'Submitting...' : 'Submit Answer'}
									</button>
								{:else}
									{#if isLastQuestion}
										<button
											on:click={handleCompleteSession}
											class="px-6 py-2 rounded-lg font-medium bg-green-600 text-white hover:bg-green-700 transition"
										>
											Complete Session
										</button>
									{:else}
										<button
											on:click={handleNext}
											class="px-6 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 transition"
										>
											Next Question
										</button>
									{/if}
								{/if}
							</div>
						</div>
					</div>
				</div>

				<!-- Sidebar -->
				<div class="space-y-6">
					<!-- Streak Counter -->
					{#if streak}
						<div class="bg-white rounded-lg shadow p-6">
							<h3 class="font-semibold mb-4">Current Streak</h3>
							<div class="text-center">
								<p class="text-4xl font-bold text-indigo-600">
									{streak.currentStreak}
								</p>
								<p class="text-sm text-gray-600 mt-1">consecutive correct</p>
							</div>
							<div class="mt-4 pt-4 border-t border-gray-200">
								<div class="flex justify-between text-sm">
									<span class="text-gray-600">Best Streak</span>
									<span class="font-medium">{streak.longestStreak}</span>
								</div>
								<div class="flex justify-between text-sm mt-2">
									<span class="text-gray-600">Total Answered</span>
									<span class="font-medium">{streak.totalAnswered}</span>
								</div>
								<div class="flex justify-between text-sm mt-2">
									<span class="text-gray-600">Accuracy</span>
									<span class="font-medium"
										>{streak.totalAnswered > 0
											? Math.round((streak.correctCount / streak.totalAnswered) * 100)
											: 0}%</span
									>
								</div>
							</div>
						</div>
					{/if}

					<!-- Question Navigator -->
					<div class="bg-white rounded-lg shadow p-6">
						<h3 class="font-semibold mb-4">Question Navigator</h3>
						<div class="grid grid-cols-5 gap-2">
							{#each Array(totalQuestions) as _, i}
								{@const isAnswered = answeredQuestions.has(
									questions[i]?.id
								)}
								{@const isCurrent = i === currentIndex}
								<button
									on:click={() => handleJumpToQuestion(i)}
									class="w-10 h-10 rounded text-sm font-medium transition-colors {isCurrent
										? 'bg-indigo-600 text-white'
										: isAnswered
											? 'bg-green-100 text-green-700'
											: 'bg-gray-100 text-gray-700 hover:bg-gray-200'}"
								>
									{i + 1}
								</button>
							{/each}
						</div>
					</div>
				</div>
			</div>
		</main>
	</div>
{/if}
